Fix the popup for suscription it breaks
Error: ./src/app/dashboard/subscription/page.tsx:74:4
Parsing ecmascript source code failed
[0m [90m 72 |[39m   )[33m;[39m[0m
[0m [90m 73 |[39m }[0m
[0m[31m[1m>[22m[39m[90m 74 |[39m [32m``[39m[32m`[39m[0m
[0m [90m    |[39m    [31m[1m^[22m[39m[0m

Unexpected eof
    at BuildError (http://localhost:9002/_next/static/chunks/%5Broot%20of%20the%20server%5D__3a40d6d2._.js:17247:41)
    at renderWithHooks (http://localhost:9002/_next/static/chunks/node_modules_react-dom_cjs_react-dom_development_ab7e073c.js:13260:28)
    at updateFunctionComponent (http://localhost:9002/_next/static/chunks/node_modules_react-dom_cjs_react-dom_development_ab7e073c.js:16755:32)
    at beginWork (http://localhost:9002/_next/static/chunks/node_modules_react-dom_cjs_react-dom_development_ab7e073c.js:18388:32)
    at beginWork$1 (http://localhost:9002/_next/static/chunks/node_modules_react-dom_cjs_react-dom_development_ab7e073c.js:23101:28)
    at performUnitOfWork (http://localhost:9002/_next/static/chunks/node_modules_react-dom_cjs_react-dom_development_ab7e073c.js:22402:24)
    at workLoopSync (http://localhost:9002/_next/static/chunks/node_modules_react-dom_cjs_react-dom_development_ab7e073c.js:22331:17)
    at renderRootSync (http://localhost:9002/_next/static/chunks/node_modules_react-dom_cjs_react-dom_development_ab7e073c.js:22308:21)
    at performConcurrentWorkOnRoot (http://localhost:9002/_next/static/chunks/node_modules_react-dom_cjs_react-dom_development_ab7e073c.js:21732:84)
    at workLoop (http://localhost:9002/_next/static/chunks/node_modules_69e050bc._.js:267:48)
    at flushWork (http://localhost:9002/_next/static/chunks/node_modules_69e050bc._.js:246:28)
    at MessagePort.performWorkUntilDeadline (http://localhost:9002/_next/static/chunks/node_modules_69e050bc._.js:474:35)